// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Playstore.Migrations;

#nullable disable

namespace Playstore.Migrations.Migrations
{
    [DbContext(typeof(DatabaseContext))]
<<<<<<<< HEAD:Playstore Application/Playstore.Migrations/Migrations/20240222043957_Additemmigrations.Designer.cs
    [Migration("20240222043957_Additemmigrations")]
    partial class Additemmigrations
========
    [Migration("20240222082659_Database Changed to SSMS from SQLITE3")]
    partial class DatabaseChangedtoSSMSfromSQLITE3
>>>>>>>> f86041e24b1c3a134d6c39b89b3b16b65d72c6c2:Playstore Application/Playstore.Migrations/Migrations/20240222082659_Database Changed to SSMS from SQLITE3.Designer.cs
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.AdminRequests", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AdminRequests");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("App");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.AppData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("AppFile")
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique();

                    b.ToTable("AppDatas");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.AppDownloads", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DownloadedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("UserId");

                    b.ToTable("AppDownloads");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.AppImages", b =>
                {
                    b.Property<Guid>("AppImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uniqueidentifier");
<<<<<<<< HEAD:Playstore Application/Playstore.Migrations/Migrations/20240222043957_Additemmigrations.Designer.cs

                    b.Property<Guid?>("AppInfoAppId")
                        .HasColumnType("uniqueidentifier");
========
>>>>>>>> f86041e24b1c3a134d6c39b89b3b16b65d72c6c2:Playstore Application/Playstore.Migrations/Migrations/20240222082659_Database Changed to SSMS from SQLITE3.Designer.cs

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("AppImageId");

                    b.HasIndex("AppId");

                    b.ToTable("AppImages");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.AppInfo", b =>
                {
                    b.Property<Guid>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PublisherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AppId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("AppInfo");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.AppReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AppId");

                    b.HasIndex("UserId");

                    b.ToTable("AppReviews");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

<<<<<<<< HEAD:Playstore Application/Playstore.Migrations/Migrations/20240222043957_Additemmigrations.Designer.cs
                    b.Property<string>("RefreshId")
========
                    b.Property<string>("RefreshKey")
>>>>>>>> f86041e24b1c3a134d6c39b89b3b16b65d72c6c2:Playstore Application/Playstore.Migrations/Migrations/20240222082659_Database Changed to SSMS from SQLITE3.Designer.cs
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.UserCredentials", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCredentials");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.Users", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
<<<<<<<< HEAD:Playstore Application/Playstore.Migrations/Migrations/20240222043957_Additemmigrations.Designer.cs
                        .HasColumnType("datetime2");
========
                        .HasColumnType("date");
>>>>>>>> f86041e24b1c3a134d6c39b89b3b16b65d72c6c2:Playstore Application/Playstore.Migrations/Migrations/20240222082659_Database Changed to SSMS from SQLITE3.Designer.cs

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.AdminRequests", b =>
                {
                    b.HasOne("Playstore.Contracts.Data.Entities.Users", "Users")
                        .WithMany("AdminRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.AppData", b =>
                {
                    b.HasOne("Playstore.Contracts.Data.Entities.AppInfo", "AppInfo")
                        .WithOne("AppData")
                        .HasForeignKey("Playstore.Contracts.Data.Entities.AppData", "AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppInfo");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.AppDownloads", b =>
                {
                    b.HasOne("Playstore.Contracts.Data.Entities.AppInfo", "AppInfo")
                        .WithMany("AppDownloads")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Playstore.Contracts.Data.Entities.Users", "Users")
                        .WithMany("AppDownloads")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppInfo");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.AppImages", b =>
                {
                    b.HasOne("Playstore.Contracts.Data.Entities.AppInfo", "AppInfo")
                        .WithMany("AppImages")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppInfo");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.AppInfo", b =>
                {
                    b.HasOne("Playstore.Contracts.Data.Entities.Category", "Category")
                        .WithMany("AppInfo")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Playstore.Contracts.Data.Entities.AdminRequests", "AdminRequests")
                        .WithOne("AppInfo")
                        .HasForeignKey("Playstore.Contracts.Data.Entities.AppInfo", "RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Playstore.Contracts.Data.Entities.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdminRequests");

                    b.Navigation("Category");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.AppReview", b =>
                {
                    b.HasOne("Playstore.Contracts.Data.Entities.AppInfo", "AppInfo")
                        .WithMany("AppReview")
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Playstore.Contracts.Data.Entities.Users", "Users")
                        .WithMany("AppReview")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppInfo");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("Playstore.Contracts.Data.Entities.Users", "Users")
                        .WithOne("RefreshToken")
                        .HasForeignKey("Playstore.Contracts.Data.Entities.RefreshToken", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.UserCredentials", b =>
                {
                    b.HasOne("Playstore.Contracts.Data.Entities.Users", "User")
                        .WithOne("userCredentials")
                        .HasForeignKey("Playstore.Contracts.Data.Entities.UserCredentials", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.UserRole", b =>
                {
                    b.HasOne("Playstore.Contracts.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Playstore.Contracts.Data.Entities.Users", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.AdminRequests", b =>
                {
                    b.Navigation("AppInfo");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.AppInfo", b =>
                {
                    b.Navigation("AppData");

                    b.Navigation("AppDownloads");

                    b.Navigation("AppImages");

                    b.Navigation("AppReview");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.Category", b =>
                {
                    b.Navigation("AppInfo");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Playstore.Contracts.Data.Entities.Users", b =>
                {
                    b.Navigation("AdminRequests");

                    b.Navigation("AppDownloads");

                    b.Navigation("AppReview");

                    b.Navigation("RefreshToken");

                    b.Navigation("UserRoles");

                    b.Navigation("userCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
